export * from './App/App';
// export * from './Footer/Footer';
export * from './Main/Main';
// export * from './Header/Header';
// export * from './Section/Section';
// export * from './Input/Input';
// export * from './Textarea/Textarea';
// export * from './TextsList/TextsList';
// export * from './TextsItem/TextsItem';
// export * from './Button/Button';
